// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOL5BU3bn1GDWIQkqijFpo9d0VraMRpFM',
    appId: '1:1020581351082:web:4a4a41b54fd5e2554c4ad3',
    messagingSenderId: '1020581351082',
    projectId: 'bigul-ekyc',
    authDomain: 'bigul-ekyc.firebaseapp.com',
    storageBucket: 'bigul-ekyc.appspot.com',
    measurementId: 'G-CL83ZHD7HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNhC_HTP4bcldg0Hw0z_GSWM1joSG6tRg',
    appId: '1:1020581351082:android:e984967b5afda5724c4ad3',
    messagingSenderId: '1020581351082',
    projectId: 'bigul-ekyc',
    storageBucket: 'bigul-ekyc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Fy68PtIzdlu_dqlk3-UjTKNHsTavBlQ',
    appId: '1:1020581351082:ios:b5b226584e9956e54c4ad3',
    messagingSenderId: '1020581351082',
    projectId: 'bigul-ekyc',
    storageBucket: 'bigul-ekyc.appspot.com',
    iosClientId: '1020581351082-s202vootdgqtm1rah2fs9i37oq70657p.apps.googleusercontent.com',
    iosBundleId: 'com.example.bigulEkyc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Fy68PtIzdlu_dqlk3-UjTKNHsTavBlQ',
    appId: '1:1020581351082:ios:b5b226584e9956e54c4ad3',
    messagingSenderId: '1020581351082',
    projectId: 'bigul-ekyc',
    storageBucket: 'bigul-ekyc.appspot.com',
    iosClientId: '1020581351082-s202vootdgqtm1rah2fs9i37oq70657p.apps.googleusercontent.com',
    iosBundleId: 'com.example.bigulEkyc',
  );
}
